# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."crypted-nixos".device = "/dev/disk/by-uuid/cd55bbca-074f-4527-b23a-3b110b7c0ac3";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/gnu" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@guix" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@persistent" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/3fce3464-22f1-41c4-9eac-1223ebab4e51";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/62E8-D595";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
